### ISSUE TITLE
get_buffer_window should return option

### ISSUE THREAD

**Issue by Ngoguey42** [janestreet/ecaml#10]
I had this error several times when calling `Ecaml.Windowget_buffer_window buffer` with buffers not shown in any window.

```
("funcall failed to convert return value." (symbol get-buffer-window)
 (type_ window)
 (exn
  ("unable to convert Elisp value to OCaml value" (type_ window) (value nil)
   (exn ("[window]'s [of_value_exn] got value not in subtype" nil)))))
```

**Comment by aalekseyev** [comment]
[Fixed](https://github.com/janestreet/ecaml/commit/f3be8d79f34017a937ca771b10959fbc0d3b9caa#diff-2ac830903a02a41dd59d1fcfb3731df552d8ad70603869d79f5b77daf26152dc).
