### ISSUE TITLE
Emacs's license and that of OCaml are incompatible

### ISSUE THREAD

**Issue by DemiMarie** [janestreet/ecaml#2]
OCaml – including the RTS, which every OCaml program must use – is licensed under the LGPL v2.1, while Emacs is under GPLv3+.  These two licenses are incompatible.  The OCaml linking exception doesn't substantially change things.  The result is that OCaml plugins for Emacs cannot be legally distributed.

**Comment by diml** [comment]
So one cannot release a binary plugin. What do you think should be done at the ecaml level?

**Comment by cfcs** [comment]
According to GNU they are compatible: https://www.gnu.org/licenses/license-list.html#LGPLv2.1

**Comment by yminsky** [comment]
@DemiMarie, I'm going to close this issue. Feel free to reopen if you have any references explaining the incompatibility, but for now, I don't see the issue.
