### ISSUE TITLE
Sample plugin

### ISSUE THREAD

**Issue by bikallem** [janestreet/ecaml#3]
Hi,

Is there a sample emacs plugin that is built using this package?

**Comment by dwang20151005** [comment]
No, but I'll see if we can put one together and get it released.

**Comment by gallais** [comment]
This seems relevant: https://blag.bcc32.com/ecaml-getting-started/2017/11/05/emacs-plugins-in-ocaml-1/

**Comment by yminsky** [comment]
@dwang20151005 Any progress here?

**Comment by dwang20151005** [comment]
Mitchell's been having some trouble getting ecaml to build using the external setup.  So far he's tried jbuilder, jane-build, and Aaron Zeng's method (from the bcc32 blog).

**Comment by diml** [comment]
@dwang20151005 I can help with this

**Comment by dwang20151005** [comment]
This will be released internally after the next emacs prod roll, probably next week, and on github shortly after that.

**Comment by hhugo** [comment]
@dwang20151005, is this fixed ?

**Comment by dwang20151005** [comment]
I'll look into it.  It's been released internally, but maybe I don't understand our public release process.

**Comment by trefis** [comment]
It is since https://github.com/janestreet/ecaml/commit/617628ceb0460ea9cd7e9c933f98470ee6859555 .
Thanks everyone!
