### ISSUE TITLE
Assertion failure with emacs 27, nil != NULL

### ISSUE THREAD

**Issue by hhugo** [janestreet/ecaml#6]
```
emacs --version
GNU Emacs 27.0.90
emacs: ecaml_stubs.c:397: emacs_module_init: Assertion `env->intern(env, "nil") == NULL' failed.
```

here is what the code says
```c
  // We assume that any emacs_value we get that is equal to NULL represents the value
  // [nil]. Emacs's [emacs-module.c] tells us not to assume this, so we just check it at
  // startup.
  assert(env->intern(env, "nil") == NULL);
```

**Comment by m-plamann** [comment]
It does look like emacs 27 broke this assumption we were making. 

I think we can fix this by asking emacs for the value of env->intern(env, "nil") on startup and then using that instead of NULL

**Comment by xclerc** [comment]
Fixed by https://github.com/janestreet/ecaml/commit/03524dfcd4d132d20f3bb5d12c27c1795a6968c4.
