### ISSUE TITLE
[Question] How to have a good dev setup for ecaml based plugins?

### ISSUE THREAD

**Issue by abhi18av** [janestreet/ecaml#8]
Hello `ecaml` team,

First off, thanks for this wonderful way of combining `emacs` and `ocaml`!

I was wondering whether it's possible to `live reload`an `ecaml` dynamic module once I've recompiled a dynamic module?

So far, it seems that to have an quick feedback loop, the only way is to rely on the `batch` mode i.e. starting up another instance of emacs and testing there. But that raises the problem of how to  do something more sophisticated such as manipulating `buffers` etc without the workflow being tedious.

Here's a reference 
https://github.com/jkitchin/emacs-modules#testing-modules

Please let me know what's your workflow for building bigger plugins using `ecaml`.

**Comment by dwang20151005** [comment]
We internally have these functions for reloading ecaml in the current
emacs process:

jane-unsafe-reload-ecaml
jane-really-unsafe-auto-reload-ecaml

The second one uses inotify to detect when the plugin changes and
reload automatically.

We're happy to expose these with the following caveat:

These are called unsafe because they make no effort to reconcile the
old and new ecaml states. In the common case where your state is split
between elisp and ecaml, you are nearly guaranteed to see
inconsistency. The new ecaml will allocate new values for the ecaml
state but the elisp will retain the values set by the old ecaml.

That said, our experience over the last couple of years has been that
they actually don't break everything every time. ¯\_(ツ)_/¯

Want them?


Wang

**Comment by m-plamann** [comment]
The functions Wang describes work well enough for manual testing,
but they're not usually what we use.

We prefer to write automated tests of new modes that we define.
There are examples testing ecaml's functionality in this repo
(for example: https://github.com/janestreet/ecaml/blob/master/test/test_current_buffer.ml)

We've got a few functions (that are not published on github but
definitely should be) that make this sort of automated testing
easier. A lot of our tests of some new functionality with a 
keybinding "C-x M-whatever foo" will look like:

```
let%bind () = press "key sequence to open some test buffer" in
[%expect {| test buffer contents |}];
let%bind () = press "C-x M-whatever foo" in
[%expect {| buffer contents after foo runs |}];
...
```

We've run into a few issues with this setup -- these tests run in
a batch-mode emacs, which sets up a fake emacs window at a weird
size, so some functions fail if they particularly care about
window geometry, or whether the point is visible on screen.

But for the most part, we've found this works very well for
automated testing.

**Comment by dwang20151005** [comment]
We try to automate testing as much as possible, using expect tests:

  https://github.com/janestreet/ppx_expect

Our build system knows how to run [emacs -batch] and load an emacs
plugin for testing.  Our Emacs-plugin expect tests look like any other
expect test, with interleaved code and output:

  https://github.com/janestreet/ecaml/tree/master/test

**Comment by abhi18av** [comment]
@dwang20151005 and @m-plamann , first off thanks for the quick response!

I'm really grokking the `ecaml` and I would **love** to be able to have a good feedback loop. I feel that you are using the library extensively and have built certain utilities around it, possible for you to share that or include those in the repo itself?

**Comment by abhi18av** [comment]
I understand that at scale, perhaps the `emacs batch mode` is the best option but a little bit of user-friendliness is really welcome.

**Comment by abhi18av** [comment]
Hi guys, just checking in if it's possible for you share the `reload` oriented utilities in the codebase please :)

**Comment by m-plamann** [comment]
Here are the functions:

```
(defun jane-reload-module (module)
  "load a new copy of the given module, even if it was previously
loaded in the same emacs instance"
  (let ((tmpfile (make-temp-file "/tmp/" nil ".so")))
    ;; Emacs will not reload a module if it has the same filename as an
    ;; alread-loaded module, so copy the module to a temp file first.
    (copy-file module tmpfile t)
    (unwind-protect
        (module-load tmpfile)
      (delete-file tmpfile))))

(defvar ecaml-reload-hook nil
  "Hook called after ecaml is reloaded")

(defun jane-unsafe-reload-ecaml ()
  "reload the module defining the library ecaml_plugin. If the
old ecaml plugin stored state in emacs, that state may be
inconsistent with the newly-loaded version of the plugin. This
function makes no effort to avoid this."
  (interactive)
  (let ((module (find-library-name "ecaml_plugin")))
    (ecaml-async-shutdown)
    (jane-reload-module module)
    (run-hooks 'ecaml-reload-hook)))

(setq jane-unsafe-auto-reload-ecaml-watch nil)

(defun jane-unsafe-auto-reload-ecaml ()
  "call jane-unsafe-reload-ecaml each time the file the ecaml_plugin changes"
  (interactive)
  (if (null jane-unsafe-auto-reload-ecaml-watch)
      (setq jane-unsafe-auto-reload-ecaml-watch
            (file-notify-add-watch (find-library-name "ecaml_plugin")
                                   '(change)
                                   (lambda (event)
                                     (jane-unsafe-reload-ecaml))))))

(defun jane-unsafe-auto-reload-ecaml-stop ()
  (interactive)
  (unless (null jane-unsafe-auto-reload-ecaml-watch)
    (file-notify-rm-watch jane-unsafe-auto-reload-ecaml-watch)
    (setq jane-unsafe-auto-reload-ecaml-watch nil)))
```

I'll also make these available in the actual repo here on github, but that change might take some time to make it from our internal repo onto github.

**Comment by abhi18av** [comment]
Thanks @m-plamann - I appreciate it 👍 💯 

Please feel free to close this issue now or later when the API is included in the open codebase.

**Comment by abhi18av** [comment]
Hi @m-plamann ,

It's been a while, hope you are doing great :) 

I was wondering whether these goodies are planned for the `0.15` release?
